### ISSUE TITLE
Making images in grid clickable

### ISSUE THREAD

**Issue by maryghermann** [codesweetly/react-image-grid-gallery#4]
I'm looking into potentially using this library for an ML annotation tool, but was wondering if there is an easy way to make the images in the grid selectable/multi-selectable?

**Comment by oluwatobiss** [comment]
Hey, @maryghermann, I’m really interested in your request. Could you clarify what you mean by “selectable/multi-selectable”? Do you have some examples of what you are trying to achieve? Providing as much context as possible would help me ascertain if your request is feasible.

**Comment by maryghermann** [comment]
@oluwatobiss Thanks! What I'm looking for is similar to when completing a CAPTCHA, and a user is able to select one or multiple images and then click submit
![image](https://github.com/codesweetly/react-image-grid-gallery/assets/104372395/62b381fe-c39b-4e59-a28a-b5ec8d83d4cc)

**Comment by oluwatobiss** [comment]
So, you are looking for an image gallery without a lightbox feature, with each image listening for a click event that compares the selected items with a prompt. Is this correct?

**Comment by maryghermann** [comment]
Yes that's fairly correct - the prompt is the only part that is unnecessary. I think I'm going to use react-grid-gallery, it has the selectable feature out of the box

**Comment by oluwatobiss** [comment]
Absolutely. `react-grid-gallery` looks ideal for your use case. All the best.

**Comment by oluwatobiss** [comment]
Absolutely. `react-grid-gallery` looks ideal for your use case. All the best.

**Comment by BugKiller-tech** [comment]
Dose this library support the onClick event?
for example, if user clicks the image, I need to do some action like displaying detailed modal about image.
Please let me know if it's possible.

**Comment by oluwatobiss** [comment]
> Dose this library support the onClick event? for example, if user clicks the image, I need to do some action like displaying detailed modal about image. Please let me know if it's possible.

The library’s onClick support allows users to click the image to open the lightbox modal. Your use case sounds interesting. Do you have any websites that are doing something similar? I would be happy to consider its implementation.

**Comment by BugKiller-tech** [comment]
I'm just asking the way to change onclick behavior, onclick is opening lightbox modal, but I'd like to take my own action once image is clicked. like redirecting to the detail page.

**Comment by oluwatobiss** [comment]
~No. The library does not currently allow customizing the behavior of the onClick event.~

With the React Image Grid Gallery v4 release, you can now implement your own custom lightbox or set up any action when an image is clicked. 🎉
