### ISSUE TITLE
How to set grid cols ?

### ISSUE THREAD

**Issue by nellysbr** [codesweetly/react-image-grid-gallery#5]
Hello! Idk if there's a option, but how can i set how many collums i want for this gallery ?

Sometimes i want to set a row of 3 collums instead of 2 and so on... Eventually i want to style for myself too..

Thanks in advance!

**Comment by oluwatobiss** [comment]
You can use the `columnWidth` prop.

**Comment by oluwatobiss** [comment]
@nellysbr The latest `react-image-grid-gallery` version now has a `columnCount` prop that allows you to explicitly set the number of columns in the gallery. That should solve this issue, so I will close it now. Thanks!
